version: '3.3'
services:
  db:
    hostname: localhost
    image: boatship/minimart-db:0.0.1
    network_mode: host
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: minimart
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    restart: unless-stopped
